In [1]:
import numpy as np

## Numpy Array Slicing

In [3]:
# 1- Slice elements from index 1 to index 5 from the following array:

arr = np.array([1,2,3,4,5,6,7])
arr[1:5]

array([2, 3, 4, 5])

In [4]:
# 2 - Slice elements from index 4 to the end of the array:

arr = np.array([1,2,3,4,5,6,7,8])
arr[4:]

array([5, 6, 7, 8])

In [7]:
# 3- Slice elements from the beginning to index 4 (not included):

arr = np.array([1,2,3,4,5,6,7])
arr[:4]

array([1, 2, 3, 4])

In [8]:
# 4 - Slice from the index 3 from the end to index 1 from the end:

arr = np.array([1,2,3,4,5,6,7,8])
arr[-3:-1]

array([6, 7])

In [12]:
# 5- Return every other element from index 1 to index 5

arr = np.array([1,2,3,4,5,6,7])
arr[1:5:2]

array([2, 4])

In [13]:
# 6- Return every other element from the entire array:

arr = np.array([1,2,3,4,5,6,7])
arr[::2]

array([1, 3, 5, 7])

## Slicing 2-D Array

In [15]:
# 7- From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[1, 1:4]

array([6, 7, 8])

In [25]:
# 8 - From both elements, return index 2

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[0:2,2]

array([3, 7])

In [26]:
# 9- From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1,2,3,4],[5,6,7,8]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

# Data Types in Numpy

In [27]:
# 10- Get the data type of an array object:

arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [28]:
# 11- Get the data type of an array containing strings:

arr = np.array(["apple", "banana", "orange"])
arr.dtype

dtype('<U6')

In [36]:
# 12 - Create an array with data type string

arr = np.array([1,2,3,4,5], dtype="S")
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [39]:
# 13 - Create an array with data type 4 bytes integer

arr = np.array([1,2,3,4,5], dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [40]:
# Value Error when value cannot be converted

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i')


ValueError: invalid literal for int() with base 10: 'a'

Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

In [42]:
# 14- Change data type from float to integer by using 'i' as parameter valu

arr = np.array([1.1,1.2,1.3])
new_arr = arr.astype("i")
print(new_arr)
print(new_arr.dtype)

[1 1 1]
int32


In [43]:
# 15- Change data type from float to integer by using int as parameter value

arr = np.array([1.1,1.2,1.3])
new_arr = arr.astype("int")
print(new_arr)
print(new_arr.dtype)

[1 1 1]
int32


In [46]:
#16 - Change data type from integer to boolean

arr = np.array([-1,0,1])
new_arr = arr.astype("bool")
print(new_arr)
print(new_arr.dtype)

[ True False  True]
bool


# NumPy Array Copy vs View


In [51]:
# 17 - Make a copy, change the original array, and display both arrays

arr = np.array([1,2,3])
arr2 = arr.copy()
arr2[2] = 4
print("Old Array :- ",arr)
print("New Array :- ", arr2)

Old Array :-  [1 2 3]
New Array :-  [1 2 4]


In [52]:
# 18 - Make a view, change the original array, and display both arrays

arr = np.array([1,2,3])
arr2 = arr.view()
arr2[2] = 4
print("Old Array :- ",arr)
print("New Array :- ", arr2)

Old Array :-  [1 2 4]
New Array :-  [1 2 4]


In [53]:
# 19 - Make a view, change the view, and display both arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


The original array SHOULD be affected by the changes made to the view.

In [55]:
# 20 - Print the value of the base attribute to check if an array owns it's data or not:

arr = np.array([1,2,3])

arr_copy = arr.copy()
arr_view = arr.view()

print(arr_copy.base)
print(arr_view.base)

None
[1 2 3]
