# Dimensions in NumPy Arrays

## 1 - O-D Arrays

In [1]:
import numpy as np


In [2]:
arr = np.array(75)
print(arr)
print(arr.shape)
print(arr.ndim)

75
()
0


## 2 - 1-D Arrays

In [3]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5]
(5,)
1


## 3 - 2-D Arrays

In [4]:
# 2-D Array of Varying length. need to use dtype=object parameter

arr = np.array([[1,2,3,4,5],[6,7,8,9]], dtype=object)
arr

array([list([1, 2, 3, 4, 5]), list([6, 7, 8, 9])], dtype=object)

In [5]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=object)
print(arr)
print(arr.shape)
print(arr.ndim)

[[1 2 3 4 5]
 [6 7 8 9 10]]
(2, 5)
2


## 4 - 3-D Arrays

In [6]:
arr = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(arr)
print(arr.shape)
print(arr.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


## 5 - Create a 7 Dimension Array

In [7]:
arr = np.array([1,2,3,4,5], ndmin=7)
print(arr)
print(arr.shape)
print(arr.ndim)

[[[[[[[1 2 3 4 5]]]]]]]
(1, 1, 1, 1, 1, 1, 5)
7


# Indexing in NumPy 

## 6 - Get the first element from the NumPy Array

In [8]:
arr = np.array([1,2,3,4,5])
print(arr[0])

1


## 7 - Get the Second element from NumPy Array


In [9]:
arr = np.array([1,2,3,4,5])
print(arr[1])

2


## 8 - Get third and fourth elements from the following array and add them.

In [10]:
arr = np.array([1,2,3,4,5])
print(arr[2]+arr[3])

7


## 9 - Access the element on the first row, second column

In [12]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])

2


## 10 - Access the element on the 2nd row, 5th column:

In [15]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,4])

10


## 11 - Access the third element of the second array of the first array

In [19]:
arr = np.array([[[1,2,75],[3,4,76]], [[5,6,77],[7,8,78]]])
print(arr[0,1,2])

76


## 12 - Print the last element from the 2nd dim

In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-1])

10
